### ISSUE TITLE
./ or ../ as --outdir argument in tidytable.py leads to an error

### ISSUE THREAD

**Issue by sschmutz** [ozagordi/VirMet#30]
...but it works with covplot.py (`virmet covplot --outdir ./ --organism "..."`).
I don't know if this is something which needs to be fixed (since it works with the absolute path).
This is the output I get:

```
stschmu@timavo:/analyses/VirMetResults/virmet_output_171024_M01274_0196_000000000-BF7JF$ virmet tidytable --outdir ./
Traceback (most recent call last):
  File "/opt/miniconda/bin/virmet", line 11, in <module>
    load_entry_point('VirMet==1.1.1', 'console_scripts', 'virmet')()
  File "/opt/miniconda/lib/python3.5/site-packages/virmet/__main__.py", line 120, in main
    args.func(args)
  File "/opt/miniconda/lib/python3.5/site-packages/virmet/__main__.py", line 16, in tidytable_run
    tidytable.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/virmet/tidytable.py", line 15, in main
    run = outdir.rstrip('/').split('/')[-1].split('virmet_output_')[1]
IndexError: list index out of range
```

**Comment by ozagordi** [comment]
I see. Yes, it should be something like

    run = os.path.abspath(outdir).split('/')[-1].split('virmet_output_')[1]

We can test it together.
